service: spinybushviper

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'

  customDomain:
    domainName: ${self:service}.textoing.com
    stage: ${self:provider.stage}
    basePath: ${self:provider.stage}
    certificateName: '*.textoing.com'
    createRoute53Record: false
    endpointType: 'edge'
    securityPolicy: tls_1_2

  settings:
    MDB_USERNAME: ${ssm:reenlee-mongodb-username}
    MDB_PASSWORD: ${ssm:reenlee-mongodb-password}
    MDB_DATABASE: ${ssm:reenlee-mongodb-database}-${self:provider.stage}

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  websocketsApiRouteSelectionExpression: '$request.body.route'
  region: us-east-1
  profile: reenlee-admin
  environment: ${self:custom.settings}

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-domain-manager

functions:
  signup:
    handler: src/routes/signup.handler
    events:
      - http:
          method: post
          path: /signup
          cors: true

  login:
    handler: src/routes/login.handler
    events:
      - http:
          method: post
          path: /login
          cors: true

  list_invites:
    handler: src/routes/accounts/invite.handler
    events:
      - http:
          method: post
          path: /accounts/invite
          cors: true

  find_friend:
    handler: src/routes/friends/find.handler
    events:
      - http:
          method: post
          path: /friends/find
          cors: true

  list_friends:
    handler: src/routes/friends/list.handler
    events:
      - http:
          method: post
          path: /friends/list
          cors: true

  reject_friend:
    handler: src/routes/friends/reject.handler
    events:
      - http:
          method: post
          path: /friends/reject
          cors: true

  find_room:
    handler: src/routes/rooms/find.handler
    events:
      - http:
          method: post
          path: /rooms/find
          cors: true

  list_rooms:
    handler: src/routes/rooms/list.handler
    events:
      - http:
          method: post
          path: /rooms/list
          cors: true

  list_chats:
    handler: src/routes/chats/list.handler
    events:
      - http:
          method: post
          path: /chats/list
          cors: true

  default:
    handler: src/websocket/default.handler
    events:
      - websocket: $default

  connect:
    handler: src/websocket/connect.handler
    events:
      - websocket: $connect

  disconnect:
    handler: src/websocket/disconnect.handler
    events:
      - websocket: $disconnect
