service: spinybushviper

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'

  settings:
    MDB_USERNAME: ${ssm:reenlee-mongodb-username}
    MDB_PASSWORD: ${ssm:reenlee-mongodb-password}
    MDB_DATABASE: ${ssm:reenlee-mongodb-database}-${self:provider.stage}

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  websocketsApiRouteSelectionExpression: '$request.body.route'
  region: us-east-1
  profile: reenlee-admin
  environment: ${self:custom.settings}

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  signup:
    handler: src/signup.handler
    events:
      - http:
          method: post
          path: /signup
          cors: true

  login:
    handler: src/login.handler
    events:
      - http:
          method: post
          path: /login
          cors: true

  default:
    handler: src/websocket/default.handler
    events:
      - websocket: $default

  connect:
    handler: src/websocket/connect.handler
    events:
      - websocket: $connect

  disconnect:
    handler: src/websocket/disconnect.handler
    events:
      - websocket: $disconnect
